import 'dotenv/config';

const {
  EIGHT_MEDICALS_NODE_ENV,
  EIGHT_MEDICALS_TEST_DATABASE_USER,
  EIGHT_MEDICALS_TEST_DATABASE_PASSWORD,
  EIGHT_MEDICALS_TEST_DATABASE_HOST,
  EIGHT_MEDICALS_TEST_DATABASE_NAME,
  EIGHT_MEDICALS_TEST_DATABASE_PORT,
  EIGHT_MEDICALS_TEST_DATABASE_MAX_CONNECTIONS,
  EIGHT_MEDICALS_TEST_PAPERTRAIL_PORT,
  EIGHT_MEDICALS_TEST_PAPERTRAIL_HOST,
  EIGHT_MEDICALS_TEST_DEBUG,
  EIGHT_MEDICALS_TEST_PORT,
  EIGHT_MEDICALS_TEST_DATABASE_STRING,
} = process.env;

export default {
  NODE_ENV: EIGHT_MEDICALS_NODE_ENV,
  DEBUG: EIGHT_MEDICALS_TEST_DEBUG,
  DATABASE_USER: EIGHT_MEDICALS_TEST_DATABASE_USER,
  DATABASE_PASSWORD: EIGHT_MEDICALS_TEST_DATABASE_PASSWORD,
  DATABASE_HOST: EIGHT_MEDICALS_TEST_DATABASE_HOST,
  DATABASE_NAME: EIGHT_MEDICALS_TEST_DATABASE_NAME,
  DATABASE_PORT: EIGHT_MEDICALS_TEST_DATABASE_PORT,
  DATABASE_MAX_CONNECTIONS: EIGHT_MEDICALS_TEST_DATABASE_MAX_CONNECTIONS,
  PAPERTRAIL_PORT: EIGHT_MEDICALS_TEST_PAPERTRAIL_PORT,
  PAPERTRAIL_HOST: EIGHT_MEDICALS_TEST_PAPERTRAIL_HOST,
  PORT: EIGHT_MEDICALS_TEST_PORT,
  DATABASE_URL: EIGHT_MEDICALS_TEST_DATABASE_STRING,
};
